name: test

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.0'
        channel: 'stable'
    - run: flutter --version
    
    - uses: github/super-linter@v4
        
        
